# Application configuration settings

screener:
  # Rule 1: Trend Alignment
  ema_period_short: 20
  ema_period_long: 50

  # Rule 2: Proximity to 50-Day High
  lookback_period: 50
  price_drop_percent_min: 0.0
  price_drop_percent_max: 10.0

  # Rule 3: Volume Ratio Filter
  avg_volume_lookback: 50
  volume_surge_min: 2.0
  volume_surge_max: 2.5

  # Rule 4: Price Range Filter
  min_price: 25.0
  max_price: 1500.0
  enable_max_price_limit: true # Added back for backward compatibility with failure_report.py

paths:
  stock_list_file: "stock_list.csv"
  valid_stock_list_file: "valid_stock_list.csv"
  output_dir: "outputs"
  report_dir: "outputs/reports"
  token_store_file: "token_store.json"

reporting:
  max_reports: 2

upstox:
  api_version: "v2"
