# Application configuration settings

screener:
  price_min: 20.0
  price_max: 1000.0
  volume_surge_factor: 1.5
  lookback_period: 20 # Days for high close, average volume, and EMA

paths:
  stock_list_file: "stock_list.csv"
  output_dir: "outputs"
  report_dir: "outputs/reports" # Relative to output_dir is also possible
  token_store_file: "token_store.json"

reporting:
  max_reports: 2

upstox:
  api_version: "v2"
  # Note: Credentials are read from .env file
